spring:
  application:
    name: inventario_noche

  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=inventario_noche;encrypt=true;trustServerCertificate=true
    username: inventario_app
    password: Cesde*2026
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true